volumes:
  certs: {}

services:
  flask: &flask
    build:
      context: .
      dockerfile: ./compose/production/flask/Dockerfile
    ports:
      - "5001:5001"
    platform: linux/amd64
    environment:
      RAG_AWS_ACCOUNT_ID: ${TF_VAR_aws_account_id}
      RAG_AWS_DEFAULT_REGION: ${TF_VAR_aws_region}
    image: ${TF_VAR_aws_account_id}.dkr.ecr.${TF_VAR_aws_region}.amazonaws.com/flask:latest
    command: /start

  nginx:
    image: nginx:latest
    env_file: ./.env
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /home/ec2-user/default.conf:/etc/nginx/default.conf:ro
      - ./certbot-webroot:/var/certbot/html
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - flask


